"""Storage contract shared by the local preview and cloud worker."""

from typing import Protocol


class DeckStore(Protocol):
    def open_workspace(self, owner: str = "local") -> dict: ...
    def authorize(
        self, workspace: str, capability: str, owner: str = "local"
    ) -> None: ...
    def submit(self, workspace: str, request_id: str, brief) -> dict: ...
    def snapshot(self, workspace: str, job_id: str | None = None) -> dict | None: ...
    def slide(self, workspace: str, job_id: str, index: int) -> dict: ...
    def cancel(self, workspace: str, job_id: str) -> dict: ...
    def claim(self, worker: str) -> dict | None: ...
    def heartbeat(self, job_id: str, worker: str) -> bool: ...
    def record(
        self, job_id: str, worker: str, progress: dict, *, slide: dict | None = None
    ) -> None: ...
    def finish(
        self,
        job_id: str,
        worker: str,
        status: str,
        *,
        result: dict | None = None,
        error: str | None = None,
    ) -> None: ...
